### ISSUE TITLE
default font to 8 or 10

### ISSUE THREAD

**Issue by valiander** [kaiserleib/canvas-memes#11]

**Comment by kaiserleib** [comment]
but why though?

**Comment by valiander** [comment]
when you put size 1, for example, you can't see it. users will have to play around with it to get it to work right, and then they will go somewhere else.

size looks like its in pixel, not font size? its unclear

**Comment by SoWelch** [comment]
+1

**Comment by valiander** [comment]
Additionally, it looks like the size is dependent on the image size. If you use a very long or very narrow image, the sizing gets super weird. Using this image for example
![keyboard-controls](https://cloud.githubusercontent.com/assets/5880580/20802463/fd086df6-b7a0-11e6-9737-a695ba077271.jpg)
